### ISSUE TITLE
Not Working With Samsung 

### ISSUE THREAD

**Issue by alhareth** [leolin310148/ShortcutBadger#10]
try {
			        ShortcutBadger.setBadge(getApplication(), badge);
			    } catch (ShortcutBadgeException e) {
			        //handle the Exception
			    }  

iam doing this Exactly but its not Working ??

**Comment by evgeniysharafan** [comment]
https://github.com/leolin310148/ShortcutBadger/blob/aca3858a9f2979e5ca8ce2d0606d96c15196cdb8/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/SamsungHomeBadger.java#L33

This is the reason.
You set wrong content values for update.
In old version you didn't put these values for update and put them for insert:
contentValues.put("package", getContextPackageName());
contentValues.put("class", getEntryActivityName());

**Comment by evgeniysharafan** [comment]
I've fixed it and created a pull request: https://github.com/leolin310148/ShortcutBadger/pull/16

**Comment by leolin310148** [comment]
thank you.
