### ISSUE TITLE
Huawei Badge

### ISSUE THREAD

**Issue by kun-qian** [leolin310148/ShortcutBadger#103]
I saw developer.huawei.com that give a guide of how to add badge on Huawei devices.

It seems that it should add permission and apply for a business certificate. And your lib seems didn't include these. Does it works on Huawei devices from(EMUI 4.1)?

**Comment by basitjawaidgranjur** [comment]
no it does not work on Huawei devices tested on P9 and p8 lite

**Comment by leoleohan** [comment]
Huawei P7 not supported, [my issue](https://github.com/leolin310148/ShortcutBadger/issues/117)

**Comment by leolin310148** [comment]
Huawei is not fully supported. some device works and some are not.

**Comment by ArslanAli7** [comment]
@leolin310148  can i know which Huawei devices are supported?
