### ISSUE TITLE
S3 Not working

### ISSUE THREAD

**Issue by githubsaturn** [leolin310148/ShortcutBadger#108]
Tested on S3 and S5 and it throws an exception:
`me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }`

**Comment by githubsaturn** [comment]
Is this because old Samsung badger is now not being used and default badger is being used instead. If so, can we not make it conditional so that it uses the old badger for older devices?

**Comment by egemenhamutcu** [comment]
Use [https://github.com/arturogutierrez/Badges](https://github.com/arturogutierrez/Badges)

It works fine one Samsung S3

Shame on you ShortcutBadger!

**Comment by leolin310148** [comment]
@egemenhamutcu Thanks for your advice!

**Comment by githubsaturn** [comment]
@leolin310148 
Other than the very useful recommendation made here (!), what do you think about using the SamsungBadger for these older devices? Deprecating a class without providing an alternative for those devices seems very irrational to me... We can perhaps use something like this to assign the right badger to any specific device:
https://github.com/mataanin/android-devices/blob/master/Build.Model%20-%20models.csv

**Comment by leolin310148** [comment]
@githubsaturn 
old samsung support is back and will handle better with newer version.
