### ISSUE TITLE
Not Working with "com.android.launcher"

### ISSUE THREAD

**Issue by VivekKumarApps** [leolin310148/ShortcutBadger#11]
Hello,

I am using this project on the Micromax Canvas & Nexus devices. But this is not working on those device which have "com.android.launcher".

Please tell me what is the problem? I am waiting for your response.

Thanks,
Vivek Kumar

**Comment by leolin310148** [comment]
Still not working?

**Comment by VivekKumarApps** [comment]
No, Still it is not working.

Thanks,
Vivek Kumar

**Comment by 285767358** [comment]
hello，
I‘m try to use this project. The demo has some problem, and i'm try to use it in my project.It's not working.  How to do? I'm waiting for your response. ThankU :)

**Comment by leolin310148** [comment]
What's the problem? Can you describe it?

**Comment by leolin310148** [comment]
no longer support 'com.android.launcher'
