### ISSUE TITLE
in last version 1.1.8 samsung not workung, only in 1.1.4

### ISSUE THREAD

**Issue by matanel11** [leolin310148/ShortcutBadger#114]
me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge

Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

**Comment by startandroid** [comment]
I have the same issues. Please, return Samsung badger. 
I've created pull request
#115

**Comment by hendrawd** [comment]
I have 1.1.6, and it's not working too for samsung

**Comment by an965666225** [comment]
List<ResolveInfo> receivers = packageManager.queryBroadcastReceivers(intent, 0);
this line:can not get receiver , so can not work.

**Comment by leoleohan** [comment]
I have the same issues

**Comment by andrryaka** [comment]
I have ерыу same

**Comment by HarisSistek** [comment]
Any update on this issue? Having the same problem with all my Samsung devices.

**Comment by opayen** [comment]
Issue was fixed when this pull request was merged: https://github.com/leolin310148/ShortcutBadger/pull/115
But I guess we'll have to wait for a version bump now, right @leolin310148 ?

**Comment by leolin310148** [comment]
Yes please wait for some days

**Comment by leolin310148** [comment]
1.1.13 should works!

**Comment by omar-nweave** [comment]
On Samsung Note 3, Android 5.0, 1.1.4 was Working after that till 1.1.13 Not working.
