### ISSUE TITLE
Failed to resolve: me.leolin:ShortcutBadger:1.1.6

### ISSUE THREAD

**Issue by leoleohan** [leolin310148/ShortcutBadger#116]
Failed to resolve: me.leolin:ShortcutBadger:1.1.6
Failed to resolve: me.leolin:ShortcutBadger:1.1.7
Failed to resolve: me.leolin:ShortcutBadger:1.1.8

Whatz the problem? Thank u.

**Comment by tuinui** [comment]
I got this problem too
Can you tell me how can you resolve this error? @leoleohan 
Thank you

**Comment by ludeyuan** [comment]
I got this problem too, and my way to solve is copy the code to my Project.@tuinui
