### ISSUE TITLE
Huawei : uid 10224 does not have com.huawei.android.launcher.permission.WRITE_SETTINGS.

### ISSUE THREAD

**Issue by leoleohan** [leolin310148/ShortcutBadger#117]
**Huawei P7:**
`Caused by: java.lang.SecurityException: Permission Denial: reading com.huawei.android.launcher.LauncherProvider from pid=24730, uid=10224 requires com.huawei.android.launcher.permission.WRITE_SETTINGS: uid 10224 does not have com.huawei.android.launcher.permission.WRITE_SETTINGS.
`

Then I add the permission in AndroidManifest.xml, but this error still exists.
Does this library need some else permissions that you didn't mention in README?

[Click here](https://github.com/leoleohan/LauncherBadge) to clone my test project on Github.

**Comment by jukksaar** [comment]
Huawei Y360-U61:
// ShortcutBadger called from launching activity's onPause-method:
	@Override
	protected void onPause() {
		new KolAppWidgetProvider().updateWidgetCount(getApplicationContext());
		ShortcutBadger.applyCount(this, Meks.get(this).getCountOfNewMessages()); 
[AndroidManifest.txt](https://github.com/leolin310148/ShortcutBadger/files/434175/AndroidManifest.txt)
[errorlog.txt](https://github.com/leolin310148/ShortcutBadger/files/434189/errorlog.txt)

**Comment by ice-j** [comment]
I just run into this, and adding `com.huawei.android.launcher.permission.CHANGE_BADGE` fixed the problem. I got the same error message as you on Huawei P9.

**Comment by TahaSaber** [comment]
I added these permissions and it worked perfectly.
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE"/>

**Comment by TahaSaber** [comment]
I added these permissions and it worked perfectly.
   android.permission.INTERNET
   com.huawei.android.launcher.permission.READ_SETTINGS"
   com.huawei.android.launcher.permission.WRITE_SETTINGS"
   com.huawei.android.launcher.permission.CHANGE_BADGE"

**Comment by TahaSaber** [comment]
I added this permissions and it worked perfectly.
   android.permission.INTERNET

**Comment by darknoise** [comment]
Work for me! Huawei P9 Lite
