### ISSUE TITLE
Not working in Genymotion (android 4.4.4) and Nexus 5 (android 6)

### ISSUE THREAD

**Issue by vuivenao** [leolin310148/ShortcutBadger#118]
I used this library, it worked well in Samsung devices but not worked in Genymotion and Nexus 5
Please give me a solution. Tks!

E/ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

**Comment by syndycat** [comment]
How did you fix this error ? 

Thx

**Comment by leolin310148** [comment]
Genymotion and Nexus5 uses android native launcher which is not supported anymore.
