### ISSUE TITLE
Not working with "com.android.launcher" on Nexus and Moto devices.

### ISSUE THREAD

**Issue by shoebhoney** [leolin310148/ShortcutBadger#12]
Hello,

I am having a problem, when the package is  "com.android.launcher".
Code is creating a Bitmap of badge count but not changed the app icon on Nexus and Moto devices.

Please tell me what's wrong i did.
I am appreciating your this post.

Thanks,
Shoeb Ahmed

**Comment by mourjan** [comment]
I believe the solution to that would be by adding the following to the manifest

    <uses-permission android:name="com.android.launcher.action.INSTALL_SHORTCUT" />
    <uses-permission android:name="com.android.launcher.permission.UNINSTALL_SHORTCUT" /> 

and hopefully, Leolin could add these required permissions to the readme description, cause I just got a warning of terms violation from Google, for trying to install a shortcut without acquiring the permission from users to do so.

Overall, Thank you for this great library!

**Comment by leolin310148** [comment]
permission add.

**Comment by Altman29** [comment]
permission add.  
didn't work too.
