### ISSUE TITLE
From NotificationsHandler

### ISSUE THREAD

**Issue by Hiike** [leolin310148/ShortcutBadger#121]
Is there a way to applycount from a class that extends NotificationsHandler ?
I'm using Azure to send notifications and I want to be able to update the badge number even when the app was killed by the user.

**Comment by leolin310148** [comment]
the `NotificationsHandler` you mentioned about did not provide `Context`?

**Comment by Hiike** [comment]
It does provide Context, I wasn't using correctly the lib and NotificationsHandler so nevermind.
