### ISSUE TITLE
Code Improvement 

### ISSUE THREAD

**Issue by georgiev-martin** [leolin310148/ShortcutBadger#122]
- Intents should explicitly specify the recipient. [Xiaomi](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/XiaomiHomeBadger.java#L34), [Sony](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/SonyHomeBadger.java#L57), [HTC](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/NewHtcHomeBadger.java#L31), [LG](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/LGHomeBadger.java#L29), [Default](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/DefaultBadger.java#L26), [Asus](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/AsusHomeLauncher.java#L27), [Apex](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/ApexHomeBadger.java#L28), [Adw](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/AdwHomeBadger.java#L28), [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L106).

- Log lines should be printed out in debug mode only: [Huawei](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/HuaweiHomeBadger.java#L26), [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L55).

- LOG_TAGs should be hardcoded, because ProGuard may mangle the content: [Huawei](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/HuaweiHomeBadger.java#L20).

- Exceptions shouldn't be silently skipped: [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L119).

**Comment by leolin310148** [comment]
feel free to modify and send PR.
