### ISSUE TITLE
Badge applies but the method throws exception on MIUI 8

### ISSUE THREAD

**Issue by varunrramani** [leolin310148/ShortcutBadger#126]
The Badge Applies fine on MIUI 8 devices but `ShortcutBadger.applyCountOrThrow(Context, count);` throws exception. I'm using the latest version i.e. 1.1.9. Same issue was also seen on 1.1.8

Following is the Exception log.
`09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err: me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:77)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.mirraw.android.Utils.Utils.applyNotificationCount(Utils.java:1245)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.mirraw.android.database.NotificationsManager.unseenNotificationReadSuccess(NotificationsManager.java:437)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.mirraw.android.async.GetUnseenNotificationsAsync.onPostExecute(GetUnseenNotificationsAsync.java:38)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.mirraw.android.async.GetUnseenNotificationsAsync.onPostExecute(GetUnseenNotificationsAsync.java:10)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:636)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.os.AsyncTask.access$500(AsyncTask.java:177)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5276)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err: Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at me.leolin.shortcutbadger.impl.XiaomiHomeBadger.executeBadge(XiaomiHomeBadger.java:41)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:75)
09-26 15:24:22.321 23462-23462/com.mirraw.android W/System.err:     ... 14 more
09-26 15:24:22.321 23462-23462/com.mirraw.android D/Utils: Count Applied Failed`

**Comment by varunrramani** [comment]
@leolin310148 any update on the issue?

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
