### ISSUE TITLE
xiaomi, oppo, vivo not support ,  Please give me a solution .  thx

### ISSUE THREAD

**Issue by DeveloperZhuG** [leolin310148/ShortcutBadger#131]

**Comment by varunrramani** [comment]
Facing same issue on xiaomi. The badge is visible but that is applied by miui and not the library. Have already created an issue here https://github.com/leolin310148/ShortcutBadger/issues/126

**Comment by NingSo** [comment]
You can refer to #132  I only tested on my own phone.

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi and Vivo in 1.1.12, please wait the new version available and help to test, thanks!
