### ISSUE TITLE
HTC M9(android 6.0) not working

### ISSUE THREAD

**Issue by mikeobser002** [leolin310148/ShortcutBadger#134]
set badge 10 ,  Toast show "Set count=10, success=success" , but badge number not show.

**Comment by Srain-z** [comment]
me too.

**Comment by leolin310148** [comment]
Hi, are you guys using htc launcher? I tested with M7 and M10 and they are working.

I created a tool for checking and reporting, it would be great you can help me to collect which launchers are support or not by using it.
You can download it from google play
[https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking](https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking)
or from the github repo
[https://github.com/leolin310148/IsBadgeWorking.Android/releases](https://github.com/leolin310148/IsBadgeWorking.Android/releases)
