### ISSUE TITLE
Not work MIUI 8.0.2.0

### ISSUE THREAD

**Issue by subbota-a** [leolin310148/ShortcutBadger#138]
field.set(miuiNotification, String.valueOf(badgeCount == 0 ? "" : badgeCount));
throw exception:
java.lang.IllegalArgumentException: field android.app.MiuiNotification.messageCount has type int, got java.lang.String

**Comment by Srain-z** [comment]
Please follow .http://dev.xiaomi.com/doc/p=3904/index.html

**Comment by zrenx** [comment]
@Srain-z The method in your link will only add the numbers up to the number already on badger.
For example, there's already "5" on badger, I want set the badger number to "4", after invoke the reflect method **setMessageCount**, the number on badger becomes "9".

Testing on XI4, MIUI version 6.7.1

**Comment by leolin310148** [comment]
Miui 8 should work with 1.1.13.
