### ISSUE TITLE
No badges on Google Pixel Launcher, Pixel XL - android 7.1

### ISSUE THREAD

**Issue by wbmoeller** [leolin310148/ShortcutBadger#139]
Model - Pixel XL
Android Version - 7.1
Build Number - NDE63P

Pixel Launcher version 7.1.1-3359438, updated on Oct 17, 2016
https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher&hl=en

**Comment by wbmoeller** [comment]
Note - as far as I can tell the Pixel Launcher doesn't support badges (yet?).

**Comment by leolin310148** [comment]
Hi, The google official launcher does not support badge.

I created a tool for checking and reporting, it would be great you can help me to collect which launchers are support or not by using it.
You can download it from google play
[https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking](https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking)
or from the github repo
[https://github.com/leolin310148/IsBadgeWorking.Android/releases](https://github.com/leolin310148/IsBadgeWorking.Android/releases)

**Comment by wbmoeller** [comment]
Yeah, I saw that after submitting - unfortunate.  Is there a feature ticket
for the Pixel Launcher somewhere I can +1?  Also sent the launcher data
with your tool.

Love your library.  Makes my life so much easier!  You've got me spoiled
though - I'm really missing the badges on our app after upgrading my
personal phone.  :-D

~ Bill
