### ISSUE TITLE
It thinks it runs on Samsung Galaxy S7 (SM-G930F) but it doesn't

### ISSUE THREAD

**Issue by awfurtado** [leolin310148/ShortcutBadger#146]
The library thinks it can run on Samsung Galaxy S7 (SM-G930F). Init runs without errors and intents are sent without errors. But the badge doesn't update. Tried the DefaultBadher and the SamsungBadger, neither worked.

Also weird: it thinks the launcher there is com.android.google.googlequicksearchbox.

**Comment by jimmychou927** [comment]
it's working well after 
insert
`
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
`
and 
`
<uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" />  
`
to AndroidManifest.xml

**Comment by jimmychou927** [comment]
it's working well after 
insert
`
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
`
`
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
`
and 
`
<uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" />  
`
to AndroidManifest.xml

**Comment by leolin310148** [comment]
Samsung has two different badge way for old and new devices, it's handled better in 1.1.12.

**Comment by awfurtado** [comment]
@jimmychou927 mentions adding:
`<uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" />`

However that permission doesn't seem to be there currently. Should it be added? @leolin310148 can you please confirm?

**Comment by SSkovboiSS** [comment]
@leolin310148 @awfurtado 
FYI, in my case it started working on Samsung devices after I added
`<uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" />`
to AndroidManifest.xml
