### ISSUE TITLE
some Sony devices crashes when call ShortcutBadger.applyCount

### ISSUE THREAD

**Issue by Bendor** [leolin310148/ShortcutBadger#150]
I get crash reports on  Sony devises  E2333,   E2303, C6903  (android 5.0):
`Fatal Exception: java.lang.SecurityException
Missing permission to insert badges
	
android.os.Parcel.readException (Parcel.java:1547)
	
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:185)
	
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:137)
	
android.content.ContentProviderProxy.insert (ContentProviderNative.java:475)
	
android.content.ContentResolver.insert (ContentResolver.java:1207)
	
android.content.AsyncQueryHandler$WorkerHandler.handleMessage (AsyncQueryHandler.java:96)
	
android.os.Handler.dispatchMessage (Handler.java:102)
	
android.os.Looper.loop (Looper.java:135)
	
android.os.HandlerThread.run (HandlerThread.java:61)`

**Comment by grebulon** [comment]
Try to add these to the manifest:

	<uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
	<uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>
