### ISSUE TITLE
Icon count not disappear!!

### ISSUE THREAD

**Issue by jjimenez0611** [leolin310148/ShortcutBadger#152]
I used you library to implement the icon badge on my app. Actually is very easy to use, but I have some doubts, for example I install in my phone the version with the implementation with the badge and set the count in 5 and everything is fine, but then uninstall the app and install the version without the badge implementation but the icon badge still appear. So my question is why?

**Comment by dstd** [comment]
Obviously the issue is in the launcher that keeps the counter even when the app was removed. Badge is not the feature of the library, the library is just for communication with launchers.

**Comment by jjimenez0611** [comment]
Ok, thanks for the answer... Now is everything clear.
