### ISSUE TITLE
发现版权问题（是阿里百川抄袭了你？还是你偷了阿里百川）

### ISSUE THREAD

**Issue by lijunhuayc** [leolin310148/ShortcutBadger#154]
本人上个项目在使用百川。前段时间发现百川的快捷方式标未读消息数存在BUG，拔出了他的源代码扫了一遍页眉怎么过于关注。
今日恰好又在做未读消息数，顺便搜了下快捷方式添加 Badge的相关文章，查到作者的此开源项目，顿觉眼熟，使用方式、方法签名居然相同。遂拉出百川SDK做了对比，相似度达到惊人的99.99%，这分明就是复制粘贴嘛。
由于此开源项目star数较高，项目时间也长，本人无法分辨雌雄，故请作者解答一下。
email：lijunhuayc@sina.com

**Comment by leolin310148** [comment]
連bug也一起抄去了你說呢

**Comment by maolubin** [comment]
@lijunhuayc 阿里的水货很多
