### ISSUE TITLE
MIUI 6+ is not supported, please add this info to README

### ISSUE THREAD

**Issue by vararg** [leolin310148/ShortcutBadger#155]
Xiaomi changed badge logic(on MIUI 6+), now it attached to notification from system tray. Application will get 1 badge for 1 notification (and if you remove 1 notification from tray then counter on application will decrease too).
According to http://dev.xiaomi.com/doc/p=3904/index.html you can change the counter for notification, but in fact, logic of this implementation is different and not suitable for library.
So unfortunately, MIUI 6+ becomes unsupportable.

A bunch of issues has been created:
https://github.com/leolin310148/ShortcutBadger/issues/153
https://github.com/leolin310148/ShortcutBadger/issues/147
https://github.com/leolin310148/ShortcutBadger/issues/144
https://github.com/leolin310148/ShortcutBadger/issues/138
https://github.com/leolin310148/ShortcutBadger/issues/126
etc.

So please, update readme file.

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
