### ISSUE TITLE
XIAOMI device with miui 7 not work

### ISSUE THREAD

**Issue by carl1990** [leolin310148/ShortcutBadger#156]
I use XIMI 5s with MIUI 7.3 and set badger count ,but not show .
I debug the code get error info 

`field android.app.MiuiNotification.messageCount has type int, got java.lang.String` in `XiaomiHomeBadger`   class  and code in 

     Field field = miuiNotification.getClass().getDeclaredField("messageCount");
     field.setAccessible(true);
     field.set(miuiNotification, String.valueOf(badgeCount == 0 ? "" : badgeCount));

**Comment by vararg** [comment]
Check this one https://github.com/leolin310148/ShortcutBadger/issues/155

**Comment by grebulon** [comment]
I use the following code:

	Class<?> miuiNotificationClass = Class.forName("android.app.MiuiNotification");
	Object miuiNotification = miuiNotificationClass.newInstance();
	Field field = miuiNotification.getClass().getDeclaredField("messageCount");
	field.setAccessible(true);
	try {
	    field.set(miuiNotification, String.valueOf(count == 0 ? "" : count));
	} catch (IllegalArgumentException ex) {
	    field.set(miuiNotification, count);
	}

**Comment by vararg** [comment]
And this solution really works for you? Because I try to use same workaround but unsuccessfully, exception disappear but badge still doesn't work.

**Comment by grebulon** [comment]
No success with badge. But on the way I discovered how to show customized picture on the notification, so it wasn't a complete waste of time...

**Comment by karthickperumal** [comment]
@grebulon Hi can you share me the link or code to Customize picture on the notification.??

**Comment by grebulon** [comment]
@karthickperumal see: http://stackoverflow.com/a/40708431/2603965

**Comment by karthickperumal** [comment]
@grebulon @vararg Is there any other way to show badge count on app icon in Xiaomi and Huwaie using Shortcut badger library??? Then how Whatsapp and Facebook n all showing the badge count on its icon , any idea about this???Please share it

**Comment by vararg** [comment]
@karthickperumal 
According to #155(check description) Xiaomi on newest MIUI will show badges only when notification in status tray attached. After removing notification badge will be removed too. (checked on skype, etc)

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
