### ISSUE TITLE
LG nexus 5x not work

### ISSUE THREAD

**Issue by carl1990** [leolin310148/ShortcutBadger#157]
on my LG nexus 5x device not work , and I see the code 

    static {
        BADGERS.add(AdwHomeBadger.class);
        BADGERS.add(ApexHomeBadger.class);
        BADGERS.add(NewHtcHomeBadger.class);
        BADGERS.add(NovaHomeBadger.class);
        BADGERS.add(SonyHomeBadger.class);
        BADGERS.add(XiaomiHomeBadger.class);
        BADGERS.add(AsusHomeLauncher.class);
        BADGERS.add(HuaweiHomeBadger.class);
        //BADGERS.add(LGHomeBadger.class);
        BADGERS.add(SamsungHomeBadger.class);
        BADGERS.add(ZukHomeBadger.class);
    }

why are you comment LGHomeBadger

**Comment by vararg** [comment]
LG nexus 5x runs on pure android(like all nexus devices). And pure android doesn't support notification badges.
