### ISSUE TITLE
Which context to use?

### ISSUE THREAD

**Issue by abalta** [leolin310148/ShortcutBadger#158]
In activity, badge counter works well but, I want to use with Firebase even app not running. In Fabase, here is my method;

`@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Log.e(TAG, "From: " + remoteMessage.getFrom());

        if (remoteMessage == null)
            return;

        // Check if message contains a notification payload.
        if (remoteMessage.getNotification() != null) {
            Log.e(TAG, "Notification Body: " + remoteMessage.getNotification().getBody());
            handleNotification(remoteMessage.getNotification().getBody());
        }

        // Check if message contains a data payload.
        if (remoteMessage.getData().size() > 0) {
            Log.e(TAG, "Data Payload: " + remoteMessage.getData().toString());

            try {
                JSONObject json = new JSONObject(remoteMessage.getData().toString());
                handleDataMessage(json);
            } catch (Exception e) {
                Log.e(TAG, "Exception: " + e.getMessage());
            }
        }

        //keepBadgeCount();
        ShortcutBadger.applyCount(getApplicationContext(), 20);
    }`

I tried, getApplicationContext(), this and MyFirebaseMessagingService.this but nothing works with these type of context.

**Comment by Corbichon** [comment]
@abalta Could you get it to work? I have the same problem here...

**Comment by abalta** [comment]
@Corbichon no I cant.

**Comment by leolin310148** [comment]
It seems not working with `FirebaseMessagingService`, maybe you can send an intent to another service and let the service handle the badge.
