### ISSUE TITLE
Badge Count not visible on Xiomi MI4I

### ISSUE THREAD

**Issue by siddharthnaik7** [leolin310148/ShortcutBadger#160]
Hi, I am using (https://github.com/phonegap/phonegap-plugin-push) plugin to set the Badge count, which uses this library of **ShortcutBadger**. Using this plugin I am able to get badge count on most of the Samsung Devices, but I am not able to get the badge count on Xiomi MI4I. Kindly, let me know, if there is any work around to get the badge count?

**_The details are as follows:_**

**Expected Behaviour:**

Using "push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);" the badge count should work.

**Actual Behaviour:**

Using "push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);" Badge count works on few Samsung based Android devices viz.: Samsung Note 3 Neo (Android- 5.1.1), etc

**Reproduce Scenario (including but not limited to):**

After registering the device for push notification, on the event of notification received, I have added:
"push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);", to set the Badge count.

**Steps to Reproduce:**

```
push.on('registration', (data) => {
//push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
console.log("device token ->", data.registrationId);
//TODO - send device token to server
});
push.on('notification', (data) => {
push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
console.log('message', data.message);
let self = this;
//if user using app and push notification comes
if (data.additionalData.foreground) {
// if application open, show popup
let confirmAlert = this.alertCtrl.create({
title: 'New Notification',
message: data.message,
buttons: [{
text: 'Ignore',
role: 'cancel'
}, {
text: 'View',
handler: () => {
//TODO: Your logic here
self.nav.push(DetailsPage, {message: data.message});
}
}]
});
confirmAlert.present();
} else {
//if user NOT using app and push notification comes
//TODO: Your logic on click of push notification directly
self.nav.push(DetailsPage, {message: data.message});
console.log("Push notification clicked");
}
});

```
**Platform and Version (eg. Android 5.0 or iOS 9.2.1):**

Android-5.0.2, 5.1.1, 6.0, 7.0

**(Android) What device vendor (e.g. Samsung, HTC, Sony...):**

Lenovo(A6000), Samsung(Note 3 Neo), Moto(G 4), Xiomi(MI4I)

**Cordova CLI version and cordova platform version:**

Cordova CLI - 6.4.0

**Cordova Platform Version Android -:**
Installed platforms:
android 6.0.0
Available platforms:
amazon-fireos ~3.6.3 (deprecated)
blackberry10 ~3.8.0
browser ~4.1.0
firefoxos ~3.6.3
webos ~3.7.0
windows ~4.4.0
wp8 ~3.8.2 (deprecated)

**Plugin version:**

Cordova plugin version | grep phonegap-plugin-push -
phonegap-plugin-push 1.8.2 "PushPlugin"

**Sample Code that illustrates the problem:**

```
push.on('registration', (data) => {
//push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
console.log("device token ->", data.registrationId);
//TODO - send device token to server
});
push.on('notification', (data) => {
push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
console.log('message', data.message);
let self = this;
//if user using app and push notification comes
if (data.additionalData.foreground) {
// if application open, show popup
let confirmAlert = this.alertCtrl.create({
title: 'New Notification',
message: data.message,
buttons: [{
text: 'Ignore',
role: 'cancel'
}, {
text: 'View',
handler: () => {
//TODO: Your logic here
self.nav.push(DetailsPage, {message: data.message});
}
}]
});
confirmAlert.present();
} else {
//if user NOT using app and push notification comes
//TODO: Your logic on click of push notification directly
self.nav.push(DetailsPage, {message: data.message});
console.log("Push notification clicked");
}
});
```

Thanks - Sid

**Comment by vararg** [comment]
According to https://github.com/leolin310148/ShortcutBadger/issues/155 please check MIUI version on Xiomi MI4I.

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
