### ISSUE TITLE
badger not support xiaomi and huawei

### ISSUE THREAD

**Issue by songwj1989** [leolin310148/ShortcutBadger#162]
when i set count, samsung is successful, but xiaomi and huawei failed. xiaomi and huawei have themself methods?

**Comment by PINOLA** [comment]
while huawei Mate9 is failed but huawei6plus is successful,maybe you can set the permission .

**Comment by karthickperumal** [comment]
Am also facing the same issue on Xiaomi and huwai devices.
if got any idea please share it

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!

**Comment by karthickperumal** [comment]
Thanks !! Am waiting ;)
