### ISSUE TITLE
Not working in some Samsung devices

### ISSUE THREAD

**Issue by sotocast** [leolin310148/ShortcutBadger#163]
In a Samsung Grand Prime not show the badge

**Comment by jimmychou927** [comment]
add  <uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" /> to AndroidManifest.xml

**Comment by BrokenTeeth** [comment]
I got same problem. 

I'm using galaxy s7 and 7.0 nougat .

not working for me

**Comment by sotocast** [comment]
Thanks. I solved the issue. I used the version 1.1.8 and work fine!
