### ISSUE TITLE
Android 6.0.1 - Sony 

### ISSUE THREAD

**Issue by oliverfogden** [leolin310148/ShortcutBadger#168]
I use ShortcutBadger through the phonegap-plugin-push plugin. Historically I had no problems with my phone (Sony E6653) displaying badges when it was running 5.1.1 but after having upgraded I am no longer able to update the badge.

Running the plugin's setApplicationIconBadgeNumber function does strangely result in the success callback being run, but no badge is shown. **IsBadgeWorking** does work on the device and is able to set a badge. 

I believe phonegap-plugin-push uses ShortcutBadger 1.1.11 

The issue I've raised on phonegap-plugin-push: https://github.com/phonegap/phonegap-plugin-push/issues/1560

**Comment by leolin310148** [comment]
Hi @oliverfogden 
maybe you need to ask the phonegap-plugin-push to update the Shortcutbadger

**Comment by macdonst** [comment]
@leolin310148 What version of ShortcutBadger should I be using? I'm including 1.1.11 with the plugin, is there an update?

**Comment by macdonst** [comment]
@leolin310148 ah, now I see that .12 is now available. I'll update and have the user re-test.

**Comment by macdonst** [comment]
@leolin310148 @oliverfogden and I upgraded to 1.1.12 and the problem still exists. How can we debug, collect logs, etc?

**Comment by Jolete** [comment]
Hi, I have a Sony Xperia™ Z3 and the Badge has not showed. I can see the push.setApplicationIconBadgeNumber() function is called but I cannot see any badge. I'm working with phonegap/phonegap-plugin-push plugin. 

Could I do something to resolve this problem?

Regards
