### ISSUE TITLE
does not work on Samsung S4

### ISSUE THREAD

**Issue by rafalsk** [leolin310148/ShortcutBadger#17]
Hello 

try {
                        badgeCount++;
                        ShortcutBadger.setBadge(getApplicationContext(), badgeCount);
                    } catch (ShortcutBadgeException e) {
                        //handle the Exception
                    }

does not show a badge on app icon. tested on Samsung Galaxy S4. both from a service/Activity/Fragment

**Comment by leolin310148** [comment]
Still not working? Is there any error messages?
