### ISSUE TITLE
Xiaomi devices  have some bug

### ISSUE THREAD

**Issue by yung-yu** [leolin310148/ShortcutBadger#183]
when run this code,
XiaomiHomeBadger.java
```
  if (Build.MANUFACTURER.equalsIgnoreCase("Xiaomi")) {
            tryNewMiuiBadge(context, badgeCount);
        }
```

 this will show a empty notification,why this code added ?

**Comment by jkasten2** [comment]
@yung-yu This was already reported in issue https://github.com/leolin310148/ShortcutBadger/issues/170.

**Comment by yung-yu** [comment]
thanks. tell me about this, will follow this

**Comment by yung-yu** [comment]
Thanks for informing
