### ISSUE TITLE
Cannot set number over 99

### ISSUE THREAD

**Issue by ThanawatMas** [leolin310148/ShortcutBadger#19]
When number 99 and increse number badge to 100 or over 100
It throws exception can't set.
P.s. I test on Samsung device {OS: 4.1.2, 4.3, 4.4}

**Comment by leolin310148** [comment]
Yes, I set the limit as 99.

**Comment by ThanawatMas** [comment]
Excuse me, Is it possible to extend number over 99 in next version?

**Comment by ygnessin** [comment]
This should probably be documented in the README

**Comment by Saketme** [comment]
I believe it's already mentioned in the method's documentation.
