### ISSUE TITLE
Converting the Badge from circle to Rectatngle and adding float values to badge

### ISSUE THREAD

**Issue by alimirza1991** [leolin310148/ShortcutBadger#2]
Hi Sir
Sir please tell me how can i change appearance of badge from circle to rectangle also add float values to badge.and also changing background color and text color of the badge
Sir please reply as soon as possible.I tried lot of things,but was not able to change the appearance of the badge.
Thanx

**Comment by Saketme** [comment]
The badge appearance depends on the providers (Samsung, HTC, etc.) and not on this library or your app.
