### ISSUE TITLE
How to find ContentValues for update the badge of the different phone rom ?

### ISSUE THREAD

**Issue by Love5209** [leolin310148/ShortcutBadger#20]
Such as the title,  the phone just like the XiaoMi or HuaWei in China,i can not find the way to change the application icon . Can u help me? Thanks!

**Comment by leolin310148** [comment]
Hi, I don't have those phones. You can try to find XiaoMi launcher Apk and decompile it to find the way to update shortcut. I did this on LG and Sony launchers.

**Comment by leolin310148** [comment]
Add xiaomi support in 1.0.9.
