### ISSUE TITLE
Unable to execute badge

### ISSUE THREAD

**Issue by wardenlzr** [leolin310148/ShortcutBadger#207]
me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
My device is huawei，The system is Android 4.4.4。The above exception
How can I solve？

**Comment by wardenlzr** [comment]
I use 
compile "me.leolin:ShortcutBadger:1.1.16@aar"

**Comment by LvanCham** [comment]
same the question
I use
compile "me.leolin:ShortcutBadger:1.1.9@aar"

**Comment by eugenio-caicedo** [comment]
me too
I use "me.leolin:ShortcutBadger:1.1.21@aar"
