### ISSUE TITLE
ShortcutBadgerException has something to say...

### ISSUE THREAD

**Issue by stephanetrepier** [leolin310148/ShortcutBadger#21]
Here is the ShortcutBadgerException message :

Unable to execute badge:Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

My icon badge is always 1, and impossible to remove even with setBadge(context, 0) !

I'm on a Samsung Galaxy S3 with Android 4.3 and I set the badge with : 

try {
			ShortcutBadger.setBadge(getApplicationContext(), Integer.parseInt(12);
		} 
		catch (Exception e) {}

**Comment by stephanetrepier** [comment]
I fix the error via SamsungHomeBadger.java and comment the condition : 

if (entryActivityName.equals(cursor.getString(cursor.getColumnIndex("class")))) {
                        entryActivityExist = true;
}

In fact in the cursor there is only one column called "_id" (the getColumnCount on cursor says 1), so when we call cursor.getcolumnIndex("class"), the column class doesn't exist => bug

**Comment by leolin310148** [comment]
Thanks for helping, will be fix in 1.0.8.
