### ISSUE TITLE
建议放弃维护这种工程

### ISSUE THREAD

**Issue by easternHong** [leolin310148/ShortcutBadger#247]
如题。这个工程完全助长了某些产品经理气焰，给开发带来无限的维护难度。因为角标本身属于Launcher的任务，Rom厂家的事情，各种各样的手机不断地出现，问题也不断地产生。

同情你们这些没有脾气的开发，任何事情都默默地表示能够实现。到最后还是跳下自己挖的坑。可怜之人必有可恨之处。

**Comment by leolin310148** [comment]
interesting, thanks for advice.
