### ISSUE TITLE
xiaomi not working?

### ISSUE THREAD

**Issue by sleith** [leolin310148/ShortcutBadger#26]
Hi,
I test on LG it worked good.
But xiaomi it didn't. I use xiaomi 2.
Thanks

**Comment by leolin310148** [comment]
Hi Slieth, I tested with Genymotion and Miui Launcher and it works fine,  The SampleApp can show the package of the launcher. Can you use that and let me know the launcher xiaomi 2 is using?

**Comment by sleith** [comment]
Hi Leolin,
i tried SampleApp also not working.
In sample app screen, it's said launcher: com.miui.home
Thanks :)

**Comment by xingkaihu** [comment]
I tested on xiaomi2 , xiaomi3, xiaomi note. All didn't work.

**Comment by leolin310148** [comment]
Thanks, I'll try to get those phones for test.

**Comment by guoGavin** [comment]
I tested on HM NOTE 1LTETD,good work.

**Comment by nehatha** [comment]
Even i am getting the same issue with xiomi mi3.Can you please provide a solution asap.

**Comment by maddenbrain** [comment]
Tested on mi4c, mi note 2, mi4c with nova and apex - both doesn't show badge. Have you any ideas, or solutions?

**Comment by guoleigl** [comment]
xiaomi2 didn't work ,the minu version  miui7.5 Can you please provide a solution asap

**Comment by leolin310148** [comment]
mini 6+ is now supported in 1.1.13
