### ISSUE TITLE
This library don't work on Samsung, Huawei, HTC, OPPO.

### ISSUE THREAD

**Issue by TahaSaber** [leolin310148/ShortcutBadger#262]
This function work only on Xiaomi devices, Consider this issue.
Which function should be called to make ShortcutBadger work on other devices.
public static void applyNotification( Context context, Notification notification, int badgeCount )
	{
		if( Build.MANUFACTURER.equalsIgnoreCase( "Xiaomi" ) )
		{
			try
			{
				Field  field             = notification.getClass().getDeclaredField( "extraNotification" );
				Object extraNotification = field.get( notification );
				Method method            = extraNotification.getClass().getDeclaredMethod( "setMessageCount", int.class );
				method.invoke( extraNotification, badgeCount );
			}
			catch( Exception e )
			{
				if( Log.isLoggable( LOG_TAG, Log.DEBUG ) )
				{
					Log.d( LOG_TAG, "Unable to execute badge", e );
				}
			}
		}
	}

**Comment by dhaslkfha** [comment]
oppo and vivo only open for few apps
