### ISSUE TITLE
Seek advice

### ISSUE THREAD

**Issue by BreakingAll** [leolin310148/ShortcutBadger#27]
what's the main idea to write a child class extends shortcutbadger like CoolpadHomeBadger?  I got the launcher, but do not understand the main idea to write the CoolpadHomeBadger. I'm very longing for you to help. Thanks.

**Comment by leolin310148** [comment]
First you need to know whether the launcher has the feature 'badge'.
And you have to find out how to change the badge for the launcher.
Then you can implement it by extending ShortcutBadger.

**Comment by guoGavin** [comment]
how to find？
