### ISSUE TITLE
Please allow non-manufacturer launchers to use DefaultBadger for everything devices

### ISSUE THREAD

**Issue by Final12345** [leolin310148/ShortcutBadger#270]
Hi!
Sorry for my poor English!
Would you please change this section of code in ShortcutBadger.java, line 223
from:
        if (sShortcutBadger == null) {
            if (Build.MANUFACTURER.equalsIgnoreCase("ZUK"))
                sShortcutBadger = new ZukHomeBadger();
            else if (Build.MANUFACTURER.equalsIgnoreCase("OPPO"))
                sShortcutBadger = new OPPOHomeBader();
            else if (Build.MANUFACTURER.equalsIgnoreCase("VIVO"))
                sShortcutBadger = new VivoHomeBadger();
            else if (Build.MANUFACTURER.equalsIgnoreCase("ZTE"))
                sShortcutBadger = new ZTEHomeBadger();
            else
                sShortcutBadger = new DefaultBadger();
        }
to:
        if (sShortcutBadger == null) {
                sShortcutBadger = new DefaultBadger();
        }

Otherwise launchers that not included to ShortcutBadger does not have possibility to use DefaultBadger on devices manufactured by "ZUK", "OPPO", "VIVO", "ZTE".

Thank you!

**Comment by rsanjuan87** [comment]
you can made a pull request

**Comment by Final12345** [comment]
Done.
