### ISSUE TITLE
LG,ASUS don't work.......

### ISSUE THREAD

**Issue by xingkaihu** [leolin310148/ShortcutBadger#28]
I tested on LG nexus 5,ASUS A80

**Comment by leolin310148** [comment]
Hi, Can you use the SampleApp to provide the launcher name?

**Comment by xingkaihu** [comment]
what's the standard of the launcher name

**Comment by leolin310148** [comment]
I mean the packageName of the launcher.

**Comment by DimaArts** [comment]
Don't work on
Model: Asus Prime TF201
Launcher package name: com.android.launcher

**Comment by leolin310148** [comment]
not support for 'com.android.launcher '
