### ISSUE TITLE
Port to C#

### ISSUE THREAD

**Issue by alexrainman** [leolin310148/ShortcutBadger#29]
Can you do it? There's a plugin for Xamarin that may need this library: https://github.com/B1naryStudio/Xamarin.Badge

**Comment by alicint** [comment]
I have already ported it to C# and it works great, let me know if you still want it so I can send it to you.

**Comment by alexrainman** [comment]
I did domething too. Lets put it together :)

**Comment by wcoder** [comment]
Hi

I'm ported: https://github.com/wcoder/ShortcutBadger

**Comment by alexrainman** [comment]
Well, it seems we have a lot now. Take a look what i did. Its modular and i added support for multiple launchers: https://github.com/alexrainman/Xamarin.Badge

**Comment by wcoder** [comment]
@alexrainman, great job!
I have a few questions:

- Your plugin is available via Nuget?
- What do you think to merge the changes with https://github.com/B1naryStudio/Xamarin.Badge ?

**Comment by alexrainman** [comment]
Not available as NuGet yet as i am not the original author. I asked to merge a long time ago both not answer about it, so, i will make it available as NuGet soon with other plugins i have.

**Comment by wcoder** [comment]
Great, thanks, I will wait for your Nuget package.
