### ISSUE TITLE
v1.1.21 is not working on Samsung Galaxy S9

### ISSUE THREAD

**Issue by Onkarn92** [leolin310148/ShortcutBadger#292]
Hi Leo,

Details:
Model number: SM-G960F
Android: 8.0.0
Samsung Experience Version: 9.0

I tried with ShortcutBadger app and it is not working on S9, I tried to submit a working status by clicking on "No" button, But the app is showing "Something went wrong" toast.

Any help would be appreciated!

Cheers,
Onkar

**Comment by mubasshir** [comment]
+1

**Comment by firemaples** [comment]
After Samsung Android 8.0, the badge count was counted by OS from notification count.
You only can control the badge by set number in notifications.

Reference: 
https://developer.android.com/training/notify-user/badges#set_custom_notification_count

**Comment by firemaples** [comment]
#266

**Comment by Onkarn92** [comment]
Okay, thanks @firemaples

**Comment by guidedways** [comment]
@Onkarn92 were you able to get this to work as advised? I don't have a Samsung phone to test this on but users report that the badge isn't working on Samsung phones.

**Comment by Onkarn92** [comment]
@guidedways Yep, It is working fine with `setNumber(count)` method for notification.

> I don't have a Samsung phone to test this on but users report that the badge isn't working on Samsung phones.

On pre-Oreo Samsung phones, The ShortcutBadger should work (at lease working in my case). 
Well, You'll need to use the notification if the Android version is 8.0.0 +

**NOTE:** If notification gets cleared from notification stack, then OS will remove the badge count.

**Comment by guidedways** [comment]
@Onkarn92  Can you please share with me a screenshot of what you see when `setNumber()` is used? Does the user see a red badge similar to pre-Oreo days?

**Comment by Onkarn92** [comment]
@guidedways I can't upload a live screenshot at the moment, But you can refer to this:
 
![badge](https://user-images.githubusercontent.com/13253826/43016618-09ddb774-8c71-11e8-88fa-5b1895f39cc7.jpg)

It looks very similar on my s9 using `setNumber()` method. 

However, You can not change the background color of badge and to reset the count either clear your notification or use `setNumber(0)` (I'm not sure about this).

For more details:
1. [Modify a Notification Badge](https://developer.android.com/training/notify-user/badges)
2. #266
