### ISSUE TITLE
Nexus 7 SecurityException

### ISSUE THREAD

**Issue by mikewalkerjr** [leolin310148/ShortcutBadger#3]
I implemented the ShortcutBadger within my project and it is running perfectly on my Samsung Note 2 and Samsung Tab 4. I am running into an issue when running my code on a Google Nexus 7. I get the following:

FATAL EXCEPTION: main
java.lang.SecurityException: Permission Denial: writing com.android.launcher2.LauncherProvider uri content://com.android.launcher2.settings/favorites?notify=true from pid=4933, uid=10127 requires com.android.launcher.permission.WRITE_SETTINGS, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1465)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.update(ContentProviderNative.java:560)
at android.content.ContentResolver.update(ContentResolver.java:1316)
at com.shortcutBadger.impl.AndroidHomeBadger.executeBadge(AndroidHomeBadger.java:37)
at com.shortcutBadger.ShortcutBadger.setBadge(ShortcutBadger.java:74)

I have the following in my Manifest File:

```
<uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
<uses-permission android:name="com.android.launcher.permission.WRITE_SETTINGS" />
<uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE" />
<uses-permission android:name="com.htc.launcher.permission.WRITE_SETTINGS" />
<uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS" />
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
```

I have the correct permission, but something is still not happy. Any idea what could be causing this exception?

**Comment by spartygw** [comment]
This looks like a really useful little tool but a big bummer tat KitKat and Lollipop don't support it.  I'm on Lollipop and see the same thing:

E/DatabaseUtils( 1035): java.lang.SecurityException: Permission Denial: writing com.android.launcher2.LauncherProvider uri content://com.android.launcher2.settings/favorites?notify=true from pid=23381, uid=10117 requires com.android.launcher.permission.WRITE_SETTINGS, or grantUriPermission()

**Comment by rubinikuttyomkumar** [comment]
Any updates on this ?

**Comment by spartygw** [comment]
I haven't found a solution or any other working alternative for stock Google Lollipop.  If you find a working solution please post back here.

**Comment by realpunk** [comment]
+1 looking for solution

**Comment by iceliushuai** [comment]
No solution for this issue.
Because those launcher changed the permission's protected level, so we can't use this feature even we request this permission.

I found LG HOME on LG G3 with Lollipop defined the pemission
    com.android.launcher.permission.WRITE_SETTINGS
with protectionLevel = signatureOrSystem

So We only use the WRITE_SETTINGS feature if is system app, we never be signature level :)

**Comment by Liwenfu** [comment]
+1looking for solution

**Comment by Jamishon** [comment]
I met the same problem, Dose anyone have solution ?, please pop out, or maybe I should read the AOSP sourcecode
