### ISSUE TITLE
Nexus not working?

### ISSUE THREAD

**Issue by Chia-Wei-Du** [leolin310148/ShortcutBadger#30]
Hi,
I tested on HTC and Samsung both worked good.
But Nexus 5 it didn't.
Could you support Nexus series in the future?
Thanks

**Comment by mllanes** [comment]
I can confirm that it doesn't shows the badge on Nexus 4 either; it does works fine in Samsung Galaxy S4 with 5.01

**Comment by Saketme** [comment]
It depends on the launcher you're using and not the phone.

**Comment by leolin310148** [comment]
Nexus uses android native launcher which is not support.
