### ISSUE TITLE
On clearing the notifications in status bar, App count in the launcher is also cleared

### ISSUE THREAD

**Issue by devrath** [leolin310148/ShortcutBadger#344]
On clearing the notifications in status bar, App count in the launcher is also cleared - this should not happen unless i remove from inside the app

**Comment by bockc** [comment]
Hey @devrath , we're currently running into a similar issue. Did you find a way to fix it ?

**Comment by theneekz** [comment]
Also having this issue (from using inside of react-native-push-notification)
