### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by manishpatidar** [leolin310148/ShortcutBadger#35]
Not workinmg for Xiaomi and Micromax

**Comment by mauriziopinotti** [comment]
I cannot get it to work on Apex and Nova either: no exceptions but no badge.

**Comment by t-gao** [comment]
Also failed on on Apex and Nova.

**Comment by leolin310148** [comment]
should on [Apex Pro](https://play.google.com/store/apps/details?id=com.anddoes.launcher.pro&hl=zh_TW) and [TeslaUnread for Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.notifier&hl=zh_TW)

not the standard versions.
