### ISSUE TITLE
Does not work on LG

### ISSUE THREAD

**Issue by martofeld** [leolin310148/ShortcutBadger#36]
Im trying the library on the stock LG home and its not adding the badge to the app. 

The test app shows: com.lge.launcher2

**Comment by leolin310148** [comment]
@martofeld 
Hi, can you tell me which device are you using?

**Comment by martofeld** [comment]
@leolin310148 its an LG-P705 with android 4.0.3

**Comment by leolin310148** [comment]
maybe it's too old to support Badge.
