### ISSUE TITLE
DefaultBadger not reliable on Samsung S4 (5.0.1)

### ISSUE THREAD

**Issue by igrayson** [leolin310148/ShortcutBadger#40]
Using the recommended approach, I was able to set the badge icon for my app -- but only once. All future calls produced no effect and no exception. In my case, I initially set it to 10, and could not change it.

Using [your suggested code](https://stackoverflow.com/questions/20136483/how-do-you-interface-with-badgeprovider-on-samsung-phones-to-add-a-count-to-the?answertab=votes#tab-top), the query showed that indeed the later calls did not affect the badge count (remained at 10, despite my calls to `ShortcutBadger`).

However, if I manually instantiated your `@Deprecated SamsungHomeBadger`, and executed it, the badge did update as expected -- which is my current workaround.

**Comment by yofu1234** [comment]
I'm having the same problem. I'm new at coding. Can you explain in more detail how you fixed it. Like the code that I should copy into my app?

**Comment by igrayson** [comment]
Standard example usage (doesn't work for us):
```java
  int badgeCount = 1;
  ShortcutBadger.with(getApplicationContext()).count(badgeCount);
```

Instead (works for me):
```java
  int badgeCount = 1;
  SamsungHomeBadger samsungBadger = new SamsungHomeBadger(getApplicationContext());
  samsungBadger.count(badgeCount);
```

Supporting other phones:
```java
    int badgeCount = 1;

    Intent intent = new Intent(Intent.ACTION_MAIN);
    intent.addCategory(Intent.CATEGORY_HOME);
    ResolveInfo resolveInfo = context.getPackageManager().resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY);
    String currentHomePackage = resolveInfo.activityInfo.packageName;

    SamsungHomeBadger samsungBadger = new SamsungHomeBadger(getApplicationContext());
    if (samsungBadger.getSupportLaunchers().contains(currentHomePackage)) {
      samsungBadger.count(badgeCount);
    } else {
      ShortcutBadger.with(getApplicationContext()).count(badgeCount);
    }
    
```

**Comment by yofu1234** [comment]
okay, so I copied the code and put it into my sendPushNotification method but its still not working. I'm still getting the same bug. Here is my code, am I missing something?

        // Send Parse Push Notification to everyone
       protected void sendPushNotifications() {

            // Create our Installation query
            ParseQuery pushQuery = ParseInstallation.getQuery();
            //pushQuery.whereEqualTo("channels", "All");
            pushQuery.whereNotEqualTo("userId", ParseUser.getCurrentUser());

            // Send push notification to query
            ParsePush push = new ParsePush();
            push.setQuery(pushQuery); // Set our Installation query
            push.setMessage(getString(R.string.push_message, mealName.getText().toString(),
                    mealLocation.getText().toString()));
            push.sendInBackground();
 
            //+1 Badge Icon
            int badgeCount = 1;
            SamsungHomeBadger samsungBadger = new SamsungHomeBadger(getActivity().getApplicationContext());
            samsungBadger.count(badgeCount);
        
    }

**Comment by igrayson** [comment]
/shrug

`AndroidManifest.xml` permissions? https://github.com/leolin310148/ShortcutBadger/issues/49

**Comment by yofu1234** [comment]
okay, so I removed the extra permissions and it fixed most of the problems. However the badge count doesn't go above 1. Anyway to fix that?

**Comment by yofu1234** [comment]
So I even tried making it like this, with the increment badgeCount++; but it still not incrementing the badge counts. 

    private int badgeCount = 0;

         protected void addBadgeCount() {

        //@Deprecated SamsungHomeBadger
        //+1 Badge Icon
        badgeCount++;
        SamsungHomeBadger samsungBadger = new SamsungHomeBadger(getActivity().getApplicationContext());
        samsungBadger.count(badgeCount);
    }

**Comment by leolin310148** [comment]
api 21+ will use DefaultBadge and otherwise will use Samsung badge.
