### ISSUE TITLE
didn't work on xiaomi4(MIUI 7)

### ISSUE THREAD

**Issue by bigggge** [leolin310148/ShortcutBadger#42]

**Comment by qingyanjgh** [comment]
didn't work on HM 1s(MIUI 6.7.1.0(KHCCNCH))?

**Comment by chenzj-king** [comment]
i find the code in the miui docs
[http://dev.xiaomi.com/docs/appsmarket/technical_docs/badge/#miui67](http://dev.xiaomi.com/docs/appsmarket/technical_docs/badge/#miui67 "badge in Miui6")
but it just the once time when you install the apk work success.my phone is HM1S Miui7.1.3.0(KHCCNC

**Comment by leolin310148** [comment]
Upgraded to 1.1.13 and it should work (tested myself with RedMi Note4)
