### ISSUE TITLE
Doesn't work with ProGuard

### ISSUE THREAD

**Issue by Mygod** [leolin310148/ShortcutBadger#46]
I need to add these lines to make it work.

    -keep class me.leolin.shortcutbadger.impl.AdwHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.ApexHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.AsusHomeLauncher { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.DefaultBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.NewHtcHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.NovaHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.SolidHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.SonyHomeBadger { <init>(...); }
    -keep class me.leolin.shortcutbadger.impl.XiaomiHomeBadger { <init>(...); }

**Comment by pepijntb** [comment]
Had the same problem and this fixed it. Please add this to the readme.

**Comment by yofu1234** [comment]
I see in the commits that they made changes to the proguard 3 days ago, has this issue been fixed?

**Comment by pepijntb** [comment]
It should be.

**Comment by leolin310148** [comment]
@Mygod thanks.
