### ISSUE TITLE
Doesn't work on Nova Launcher / Nexus

### ISSUE THREAD

**Issue by alicint** [leolin310148/ShortcutBadger#48]
Hi
the library doesn't work on googles default launcher for nexus 4, then I installed the nova launcher and it still doesn't work.

**Comment by Mygod** [comment]
It does work on Nova Launcher here. Check your code.

**Comment by leolin310148** [comment]
should works Nova Launcher  with [TelsaUnread](https://play.google.com/store/apps/details?id=com.teslacoilsw.notifier)
