### ISSUE TITLE
Needs to add these permissions in xml. Should put this in the readme file

### ISSUE THREAD

**Issue by yofu1234** [leolin310148/ShortcutBadger#49]
<uses-permission android:name="com.android.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.android.launcher.permission.WRITE_SETTINGS"/>

    
    <uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
    <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>

    
    <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>

    
    <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>

    
    <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>

**Comment by Mygod** [comment]
I don't think that's necessary.

See this: https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/AndroidManifest.xml
