### ISSUE TITLE
Xiomi 4 shows only 1 badge count

### ISSUE THREAD

**Issue by kishukismat** [leolin310148/ShortcutBadger#52]
Hi leolin,

Whenever we increment badge count it does't increment badges. It shows only 1 as badge count.
We also debug it. Our counter incremented properly and also we set it , but it is not working. It always show 1 as badge count.

What should we do?

Phone Configurations are: Mi 4
Android Version : 5.0.2 LRX22G

**Comment by dingguanghui** [comment]
http://dev.xiaomi.com/doc/p=3904/index.html

Field field = notification.getClass().getDeclaredField(“extraNotification”);

**Comment by leolin310148** [comment]
Xiaomi should work well with 1.1.13
