### ISSUE TITLE
Not working on Nexus 5 device with android 6

### ISSUE THREAD

**Issue by darkovski88** [leolin310148/ShortcutBadger#55]
Hi, im adding this library to my app but seems its not working for Marshmallow, any idea what can be the issue here?

Here is the code i use:
`ShortcutBadger.with(mContext).count(sum);`
and in gradle:
`compile 'me.leolin:ShortcutBadger:1.1.3@aar'`

**Comment by ygnessin** [comment]
I may be mistaken but I think that Nexus 5 ships with "vanilla" factory Android, which does not support badges. Other OEMs have added Badge support specific to this platform; this library makes it easy to support all of them via a single interface.
