### ISSUE TITLE
Callback if appbadge is rendered

### ISSUE THREAD

**Issue by mallikgs** [leolin310148/ShortcutBadger#57]
Hi,

I am looking for a callback to know if the appbadge is successfully rendered on a given device? Or any other suggestion of doing the same?

**Comment by leolin310148** [comment]
There's no way to do this.

**Comment by mallikgs** [comment]
I was able to achieve this by querying the broadcast receivers in the phone. It worked fairly ok

private boolean supportAppbadge(Context context){

//query a list of device broadcasts. This is just an example
Intent i = new Intent("android.intent.action.BADGE_COUNT_UPDATE", null); 
return context.getPackageManager().queryBroadcastReceivers(i, 0).size() >0;

}
