### ISSUE TITLE
Not working on 5.1.1

### ISSUE THREAD

**Issue by mhtnguyen** [leolin310148/ShortcutBadger#59]
Hi,

I am using ShortcutBadger 1.1.4. On my test phone (samung galaxy s4 5.0.1) it is working. On my main phone (Samsung galaxy s6 edge plus 5.1.1) it does not display the count. I am using                             ShortcutBadger.applyCount(context, totalInboxUnreadCount); am I missing anything?

Thanks,

MH

**Comment by mhtnguyen** [comment]
Update: It is working with stock touchwiz launcher, I was using google now launcher.

**Comment by leolin310148** [comment]
google now launcher is not supported.
