### ISSUE TITLE
Not work on android emulator api 22 and api 23. 

### ISSUE THREAD

**Issue by Deno028** [leolin310148/ShortcutBadger#67]
I use this for my project, and test it work fine on LG & Sony z1 phone. However, when I test it on emulator Marshmallow 6.0 (api 23) and 5.0 (api 22),  Nexus 7 android 4(API 19) all the results is failed.

**Comment by devshisiyani** [comment]
I cant get this to work on the AVD. NEXUS api 23. When I call push.setApplicationIconBadgeNumber

logcat is
ShortcutBadger: Current badger:me.leolin.shortcutbadger.impl.DefaultBadger
ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

Not sure where is issue is.

**Comment by ZhaoKaiQiang** [comment]
The android original system not support badge feature

**Comment by spidfire** [comment]
Is there a way to test this ? maybe download a different launcher or something?
