### ISSUE TITLE
not working on some of the devices I have

### ISSUE THREAD

**Issue by dhavaln** [leolin310148/ShortcutBadger#69]
I tested the library on some of the devices I have and it didn't work on any of them except only one Samsung device:

| Model | Android Version | Working |
| --- | --- | --- |
| Asus Zenfone | 4.4.2 | Yes |
| Samsung S7 | 6.0.1 | Yes |
| Sony Xperia ZL | 5.1.1 | No |
| Micromax Android One | 4.4.4 | No |
| Motorola X | 6.0.1 | No |
| OnePlus One | 5.1.1 | No |
| Xiaomi Mi4i | 5.0.2 | No |
| OnePlus X | 5.1.1 | No |
| Lenovo K5 | 5.1.1 | No |

**Comment by neurospeech** [comment]
Confirmed, not working on Sony, Motorola, Lenovo, Micromax. Version 1.1.3 used to work correctly.

**Comment by dhavaln** [comment]
@neurospeech I probably used the latest version and didn't test with 1.1.3

**Comment by neurospeech** [comment]
Well, 1.1.3 does not work on any devices with 6.0, so it is also not useful, it used to work well till 5.*

**Comment by VaibhavProbity** [comment]
Can you tell me proper solution which will work in all devices? please...

**Comment by VaibhavProbity** [comment]
Its giving me ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) } this error

**Comment by Madroid2** [comment]
@VaibhavProbity Use version 1.1.4 the issue will be fixed

**Comment by leolin310148** [comment]
Sony and Xiaomi should work in 1.1.13 now.
Moto, lenovo and OnePlus is not supported.

**Comment by leolin310148** [comment]
And thank you for the detailed test! @dhavaln

**Comment by dhavaln** [comment]
@leolin310148 👍
