### ISSUE TITLE
Use applyCount from a service that has been started from alarm

### ISSUE THREAD

**Issue by devnull69** [leolin310148/ShortcutBadger#76]
Is it possible to set the badge count from inside a service that has been called from an alarm?

For example: My service checks for new videos that are available for my app. As soon as it finds them it should update the badge. Is that even possible?

I cannot seem to get the correct context there ...

**Comment by devnull69** [comment]
Ok, it was just me being extraordinarily stupid

I used a newly created Application as context instead of the service itself ... with the service as context it works!

**Comment by Corbichon** [comment]
@devnull69 Could you post the snippet of your service calling the badger ?
I have a very simple service (Firebase) which send notification. 
But I can't get working the 
```
@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Log.d(TAG, "Setting badge notification");
        ShortcutBadger.applyCount(this, 1);
    }
ShortcutBadger.applyCount(this, 1);
```

**Comment by avik1990** [comment]
> @devnull69 Could you post the snippet of your service calling the badger ?
> I have a very simple service (Firebase) which send notification.
> But I can't get working the
> 
> ```
> public class MyFirebaseMessagingService extends FirebaseMessagingService {
>     @Override
>     public void onMessageReceived(RemoteMessage remoteMessage) {
>         Log.d(TAG, "Setting badge notification");
>         ShortcutBadger.applyCount(this, 1);
>     }
> }
> ```
> It works when app is in foreground but not when in background...

Yes, I am also facing the same issue. Have you guys solved it? Please help
