### ISSUE TITLE
This not show badger on HuaWei  Devices... can you help me?

### ISSUE THREAD

**Issue by huangjinlangzi** [leolin310148/ShortcutBadger#78]
This not show badger on HuaWei Devices... can you help me?

**Comment by yufan2014** [comment]
在别的手机上也不可以，没找到一个可以实现图标消息数提醒的手机，楼主在哪个手机上可以？

**Comment by roveim** [comment]
华为的角标开发文档：http://developer.huawei.com/cn/consumer/wiki/index.php?title=%E5%8D%8E%E4%B8%BA%E6%A1%8C%E9%9D%A2%E8%A7%92%E6%A0%87%E5%BC%80%E5%8F%91%E6%8C%87%E5%AF%BC%E4%B9%A6

**Comment by yufan2014** [comment]
谢谢

**Comment by leolin310148** [comment]
yes, Huawei is not fully supported yet.
