### ISSUE TITLE
Get current badge count

### ISSUE THREAD

**Issue by raysango** [leolin310148/ShortcutBadger#79]
Is there any way to get the current badge count on Android device?

**Comment by JoeKaldas** [comment]
It's not supported at the moment.
So what you can do is save the count in the SharedPreferences and update it whenever you update the badge.
So now you always have the current badge count.

**Comment by egaviriarestrepo** [comment]
private static final String LAUNCHER_BADGE = "LAUNCHER_BADGE";
    private static final String CURRENT_BADGE = "CURRENT_BADGE";
    private static LauncherBadgeService instance;

    public static LauncherBadgeService getInstance() {
        if (instance == null)
            instance = new LauncherBadgeService();
        return instance;
    }

    private int getCacheCurrentLauncherBadge(Context ctx) {
        SharedPreferences settings = ctx.getSharedPreferences(LAUNCHER_BADGE, Context.MODE_PRIVATE);
        return settings.getInt(CURRENT_BADGE, 0);
    }

    private void setCacheCurrentLauncherBadge(Context ctx, int badgeCount) {
        SharedPreferences settings = ctx.getSharedPreferences(LAUNCHER_BADGE, Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = settings.edit();

        editor.putInt(CURRENT_BADGE, badgeCount);
        editor.apply();
    }

    public void setLauncherBadge(Context ctx, int badge) {
        ShortcutBadger.applyCount(ctx, badge); //for 1.1.4+
        this.setCacheCurrentLauncherBadge(ctx, badge);
    }

    public void addBadge(Context ctx) {
        int current = this.getCacheCurrentLauncherBadge(ctx);
        this.setLauncherBadge(ctx, current + 1);
    }

    public void lessBadge(Context ctx) {
        int current = this.getCacheCurrentLauncherBadge(ctx);
        if (current > 0)
            this.setLauncherBadge(ctx, current - 1);
    }

**Comment by AdnanAshraf-gol** [comment]
any update on this issue ?
