### ISSUE TITLE
Do not support com.android.launcher3

### ISSUE THREAD

**Issue by minhdangoz** [leolin310148/ShortcutBadger#8]
Please support the new Android stock Launcher.

**Comment by symbiat** [comment]
Probably the static name for `com.google.android.googlequicksearchbox` should be renamed to something different from `HOME_PACKAGE_ANDROID3`, then we can add:
`private static final String HOME_PACKAGE_ANDROID2 = "com.android.launcher3";`

**Comment by minhdangoz** [comment]
I will try, thank you very much !

**Comment by leolin310148** [comment]
cannot support com.android.launcher3
