### ISSUE TITLE
How to run project?

### ISSUE THREAD

**Issue by liang3472** [leolin310148/ShortcutBadger#82]
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by estysherman** [comment]
i had the same problem.
try this:
Remove this line from the build.gradle on the specified project:

 apply from: 'https://raw.github.com/twotoasters/gradle-mvn-push/master/gradle-mvn-push.gradle'
