### ISSUE TITLE
andriod 5.1.1 sumsung s6. - unable to resolve BADGE_COUNT_UPDATE

### ISSUE THREAD

**Issue by devshisiyani** [leolin310148/ShortcutBadger#87]
I am attempting to use ShortcutBadger to display count.
When I call ShortcutBadger.applyCount(context, badgeCount);

the logcat gives me:
phonegap.helloworld D/ShortcutBadger: Finding badger
phonegap.helloworld D/ShortcutBadger: Current badger:me.leolin.shortcutbadger.impl.DefaultBadger
phonegap.helloworld E/ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

andriod 5.1.1 sumsung s6. Get Current badger:me.leolin.shortcutbadger.impl.DefaultBadger
On does anyone know why I am getting error Unable to execute badge
let me know if more infor is required

**Comment by contrudar** [comment]
Met the same issue when used 1.1.5. Then I switched to 1.1.4 and it worked

**Comment by devshisiyani** [comment]
Thanks for that information. You correct 1.1.4 works on my Samsung s6. However tried 1.1.4 on AVD emulator and that does not work. Not sure why. Need to find out what the difference is between 1.1.4 and 1.1.5

**Comment by devshisiyani** [comment]
For version 1.1.5
In file BroadcastHelper.java found out that statement below returns list of size 0. Not sure why and whats it trying to achieve. Can anyone help
List<ResolveInfo> receivers = packageManager.queryBroadcastReceivers(intent, 0);

**Comment by yamissa** [comment]
Indeed, in the version 1.1.5 a checking has been added to verify if a receiver is available for the intent [BADGE_COUNT_UPDATE.](https://developer.android.com/reference/android/content/pm/PackageManager.html#queryBroadcastReceivers(android.content.Intent, int)). This intent allows to increment the badge counter for the samsung devices. I don't know why in some cases the returned list is empty by mistake so the intent is never broadcasted. Only working solution utile a fix, use the version 1.1.4.

**Comment by Ranjan101** [comment]
Thanks for that information. You correct 1.1.4 works .

**Comment by leolin310148** [comment]
Samsung should be well handled in 1.1.12.
