### ISSUE TITLE
You should revert back to not checking for broadcast revolvers. Major issue with Samsung launchers

### ISSUE THREAD

**Issue by borax12** [leolin310148/ShortcutBadger#93]
Samsung launchers are facing a big time issue with badge not updating as unfortunately the intent resolution query doesn't return any export receivers. 

30k users facing a problem so I guess you should remove the check for now.

**Comment by devshisiyani** [comment]
Using version 1.1.7 the emulator I use (AVD) has the same problem. The function below returns zero for all devices. Tried NEXUS, Samsung,HTC etc. However 1.1.5 works but uses different call.
public class BroadcastHelper {
	public static boolean canResolveBroadcast(Context context, Intent intent) {
		PackageManager packageManager = context.getPackageManager();
		List<ResolveInfo> receivers = packageManager.queryBroadcastReceivers(intent, 0);
		return receivers != null && receivers.size() > 0;
	}
}

**Comment by mahdihijazi** [comment]
Seems Samsung did register their broadcasts programmatically and through the AndroidManifest
https://groups.google.com/d/msg/android-developers/IFn--rwK8dg/YGcqS7LN0V8J

**Comment by contrudar** [comment]
I just uncommented this line of code https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L37

and now it works, I have no idea why SamsungHomeBadger is deprecated, but for me it was a fast bug fix.

**Comment by leolin310148** [comment]
Samsung is support better in 1.1.12.
