### ISSUE TITLE
Xiaomi 2sc unable to resolve intent

### ISSUE THREAD

**Issue by a598799539** [leolin310148/ShortcutBadger#96]
E/ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }

**Comment by xxshuaige** [comment]
Me too!

**Comment by xxshuaige** [comment]
me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
