### ISSUE TITLE
1.1.7 not compile?

### ISSUE THREAD

**Issue by hrizn** [leolin310148/ShortcutBadger#97]
why compile 'me.leolin:ShortcutBadger:1.1.7'  not working? isn't it the newest virsion is 1.1.7?

**Comment by mlabarca** [comment]
I think the package name is at 1.1.6 even if the repository is at 1.1.7.

**Comment by Holstie** [comment]
It seems like the newest 1.1.7 haven't been uploaded to the maven central.
You can download the project here from git instead.

**Comment by ygnessin** [comment]
@leolin310148 could you please publish 1.1.7 to maven central? Thanks for the great library!

**Comment by Erichkko** [comment]
@leolin310148  could you please publish 1.1.7 to maven central? Thanks for the great library!

**Comment by leolin310148** [comment]
sorry, have been busy recently. will publish soon!
